package com.example.bofteam24;

import android.content.Context;

import androidx.room.Room;
import androidx.test.core.app.ApplicationProvider;
import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.ext.junit.runners.AndroidJUnit4;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

import com.example.bofteam24.db.AppDatabase;
import com.example.bofteam24.db.CourseDao;
import com.example.bofteam24.db.CourseRoom;
import com.example.bofteam24.db.User;
import com.example.bofteam24.db.UserDao;

import java.io.IOException;

/**
 * Instrumented test, which will execute on an Android device.
 *
 * @see <a href="http://d.android.com/tools/testing">Testing documentation</a>
 */
@RunWith(AndroidJUnit4.class)
public class DatabaseTesting {
    private UserDao userDao;
    private CourseDao courseDao;
    private AppDatabase db;

    @Before
    public void createDb() {
        Context context = ApplicationProvider.getApplicationContext();
        db = Room.inMemoryDatabaseBuilder(context, AppDatabase.class).build();
        userDao = db.userDao();
        courseDao = db.courseDao();
    }

    @After
    public void closeDb() throws IOException {
        db.close();
    }

    @Test
    public void testInsertUser() {
        User user1 = new User("0", "Kirtan", "kirtan_profile.url", 0);
        User user2 = new User("1", "Brett", "brett_profile.url", 0);

        userDao.insert(user1);
        userDao.insert(user2);

        assertEquals(2, userDao.count());
    }

    @Test
    public void testDeleteUser() {
        User user1 = new User("0", "Kirtan", "kirtan_profile.url", 0);
        User user2 = new User("1", "Brett", "brett_profile.url", 0);

        userDao.insert(user1);
        userDao.insert(user2);
        userDao.delete(user2);

        assertEquals(1, userDao.count());
    }

    @Test
    public void testInsertCourse() {
        CourseRoom course1 = new CourseRoom(null, "0", "CSE 11 FALL 2020");
        courseDao.insert(course1);


        CourseRoom course2 = new CourseRoom(null, "0", "CSE 12 WINTER 2021");
        courseDao.insert(course2);


        CourseRoom course3 = new CourseRoom(null, "1", "CSE 11 FALL 2020");
        courseDao.insert(course3);


        CourseRoom course4 = new CourseRoom(null, "1", "CSE 12 WINTER 2021");
        courseDao.insert(course4);

        assertEquals(4, courseDao.count());
    }

    @Test
    public void testDeleteTwoCourses() {
        CourseRoom course1 = new CourseRoom(null,"0", "2020 FALL CSE 11");
        CourseRoom course2 = new CourseRoom(null, "0", "2021 WINTER CSE 12");
        CourseRoom course3 = new CourseRoom(null, "1", "2020 FALL CSE 11");
        CourseRoom course4 = new CourseRoom(null, "1", "2021 WINTER CSE 12");

        long course1_id = courseDao.insert(course1);
        long course2_id = courseDao.insert(course2);
        long course3_id = courseDao.insert(course3);
        long course4_id = courseDao.insert(course4);
        courseDao.delete(courseDao.get((int)course2_id));
        courseDao.delete(courseDao.get((int)course3_id));

        assertEquals(2, courseDao.count());
    }

    @Test
    public void testDeleteOneCourse() {
        CourseRoom course1 = new CourseRoom(null,"0", "2020 FALL CSE 11");
        CourseRoom course2 = new CourseRoom(null, "0", "2021 WINTER CSE 12");
        CourseRoom course3 = new CourseRoom(null, "1", "2020 FALL CSE 11");
        CourseRoom course4 = new CourseRoom(null, "1", "2021 WINTER CSE 12");

        long course1_id = courseDao.insert(course1);
        long course2_id = courseDao.insert(course2);
        long course3_id = courseDao.insert(course3);
        long course4_id = courseDao.insert(course4);

        courseDao.delete(courseDao.get((int)course1_id));

        assertEquals(3, courseDao.count());
    }

    @Test
    public void testAutoGeneratedKeys() {
        CourseRoom course1 = new CourseRoom(null,"0", "2020 FALL CSE 11");
        CourseRoom course2 = new CourseRoom(null, "0", "2021 WINTER CSE 12");

        Long course1_id = courseDao.insert(course1);
        Long course2_id = courseDao.insert(course2);

        assertNotEquals(course1_id, course2_id);
    }
}
